//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        public Bancos()
        {
            this.EmpresaBancos = new HashSet<EmpresaBancos>();
            this.ProveedorBancos = new HashSet<ProveedorBancos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<EmpresaBancos> EmpresaBancos { get; set; }
        public virtual ICollection<ProveedorBancos> ProveedorBancos { get; set; }
    }
}
