//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrarecibo
    {
        public Contrarecibo()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaPago { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
