//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioPermisos
    {
        public FormularioPermisos()
        {
            this.PerfilPermisos = new HashSet<PerfilPermisos>();
        }
    
        public int Id { get; set; }
        public int FormularioId { get; set; }
        public int PermisosId { get; set; }
    
        public virtual Formulario Formulario { get; set; }
        public virtual Permisos Permisos { get; set; }
        public virtual ICollection<PerfilPermisos> PerfilPermisos { get; set; }
    }
}
