//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        public Formulario()
        {
            this.FormularioPermisos = new HashSet<FormularioPermisos>();
        }
    
        public int Id { get; set; }
        public int ModuloId { get; set; }
        public string Nombre { get; set; }
        public string Forma { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual ICollection<FormularioPermisos> FormularioPermisos { get; set; }
    }
}
