//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosAdministrativos
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Factura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public double Importe { get; set; }
        public string Observaciones { get; set; }
        public string NoReferencia { get; set; }
        public int TipoPagoId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> EmpresaBancosId { get; set; }
        public int ConceptoId { get; set; }
        public Nullable<bool> Compartido { get; set; }
    
        public virtual Conceptos Conceptos { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EmpresaBancos EmpresaBancos { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
