//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorBancos
    {
        public int Id { get; set; }
        public int ProveedorId { get; set; }
        public int BancosId { get; set; }
        public string NoCuenta { get; set; }
        public string CLABE { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
