//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Factura = new HashSet<Factura>();
            this.ProveedorBancos = new HashSet<ProveedorBancos>();
        }
    
        public int Id { get; set; }
        public string NombreFiscal { get; set; }
        public string NombreComercial { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string RFC { get; set; }
        public string PlazoCredito { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<ProveedorBancos> ProveedorBancos { get; set; }
    }
}
