//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReposicionGastos
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoPagoId { get; set; }
        public string Referencia { get; set; }
        public int FacturaId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> EmpresaBancosId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual EmpresaBancos EmpresaBancos { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
