//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeisaBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.CajaChica = new HashSet<CajaChica>();
            this.Obra = new HashSet<Obra>();
            this.VehiculoCajaChicaDetalle = new HashSet<VehiculoCajaChicaDetalle>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> TipoEmpleado { get; set; }
    
        public virtual ICollection<CajaChica> CajaChica { get; set; }
        public virtual ICollection<Obra> Obra { get; set; }
        public virtual ICollection<VehiculoCajaChicaDetalle> VehiculoCajaChicaDetalle { get; set; }
    }
}
