//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeisaBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.CajaChicaDetalle = new HashSet<CajaChicaDetalle>();
            this.EmpresaBancos = new HashSet<EmpresaBancos>();
            this.GastosAdministrativos = new HashSet<GastosAdministrativos>();
            this.Obra = new HashSet<Obra>();
            this.Pagos = new HashSet<Pagos>();
            this.ReposicionGastos = new HashSet<ReposicionGastos>();
        }
    
        public int Id { get; set; }
        public string NombreFiscal { get; set; }
        public string NombreComercial { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string RFC { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual ICollection<CajaChicaDetalle> CajaChicaDetalle { get; set; }
        public virtual ICollection<EmpresaBancos> EmpresaBancos { get; set; }
        public virtual ICollection<GastosAdministrativos> GastosAdministrativos { get; set; }
        public virtual ICollection<Obra> Obra { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<ReposicionGastos> ReposicionGastos { get; set; }
    }
}
