//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeisaBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaBancos
    {
        public EmpresaBancos()
        {
            this.CajaChicaDetalle = new HashSet<CajaChicaDetalle>();
            this.GastosAdministrativos = new HashSet<GastosAdministrativos>();
            this.Pagos = new HashSet<Pagos>();
            this.ReposicionGastos = new HashSet<ReposicionGastos>();
        }
    
        public int Id { get; set; }
        public int EmpresaId { get; set; }
        public int BancosId { get; set; }
        public string NoCuenta { get; set; }
        public string CLABE { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> FolioInicial { get; set; }
        public Nullable<int> FolioActual { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual ICollection<CajaChicaDetalle> CajaChicaDetalle { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<GastosAdministrativos> GastosAdministrativos { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<ReposicionGastos> ReposicionGastos { get; set; }
    }
}
