//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeisaBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public Pagos()
        {
            this.PagosFactura = new HashSet<PagosFactura>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoPagoId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> EmpresaBancosId { get; set; }
        public string Referencia { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual EmpresaBancos EmpresaBancos { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PagosFactura> PagosFactura { get; set; }
    }
}
