//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeisaBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Contrarecibo = new HashSet<Contrarecibo>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int Id { get; set; }
        public int PerfilId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Activo { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<Contrarecibo> Contrarecibo { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
